server: 
  port: ${PORT:8888}

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Apallapu/Config-Repo.git
          username: Apallapu
          password: Ankamma@123
          timeout: 4
          

security:
  basic:
    enabled: false
management:
  security:
    enabled: false
